baseURL = "http://example.com/"
languageCode = "en-us"
title = "Minimal-esque"
theme = "minimal-esque"
googleAnalytics = ""

[params]
    author = "Jeffrey Summers"
    description = "Personal dark blog theme powered by Hugo & a modified Minimal theme"
    githubUsername = "#"
    accent = "#318c63"
    showBorder = true
    # backgroundColor = "#1d1d1d"
    # font = "Cabin" # should match the name on Google Fonts! Removed b/c I want to control the weights.
    highlight = true
    highlightStyle = "tomorrow-night"
    highlightLanguages = ["js", "html", "css", "sass"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

# not used - keeping as reference for future changes
# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

# [[menu.icon]]
#     url = "https://github.com/username/"
#     name = "github"
#     weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
